quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/qlphim
quarkus.hibernate-orm.database.generation=none

mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=https://film-management.org/issuer
smallrye.jwt.new-token.issuer=https://film-management.org/issuer