quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=1801062012
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/qlphim
quarkus.hibernate-orm.database.generation=none

mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=https://film-management.org/issuer
smallrye.jwt.new-token.issuer=https://film-management.org/issuer

quarkus.http.cors.enabled=true

quarkus.http.cors.origins=http://localhost:5173

quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.cors.access-control-max-age=24H