
quarkus.http.port=8081

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=Hung0901!
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/qlphim

quarkus.hibernate-orm.database.generation=none
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://film-management.org/issuer