
quarkus.http.port=8082

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=Hung0901!
quarkus.datasource.jdbc.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/qlphim?serverTimezone=Asia/Ho_Chi_Minh

quarkus.hibernate-orm.database.generation=none
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://film-management.org/issuer

quarkus.http.cors.enabled=true

quarkus.http.cors.origins=http://localhost:5173

quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.cors.access-control-max-age=24H