quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=1801062012

quarkus.datasource.jdbc.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/qlphim?serverTimezone=Asia/Ho_Chi_Minh

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8081

quarkus.http.cors.enabled=true

quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=*
quarkus.http.cors.access-control-allow-credentials=true

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://film-management.org/issuer
smallrye.jwt.sign.key.location=privateKey.pem

cloudinary.cloud-name=dfukflgwe
cloudinary.api-key=581291543324462
cloudinary.api-secret=1FVgPByBpXhpIIqx6WMF69W53mA

